//! Reference-fixture tests for the augmented ADF / KPSS implementation
//! (Phase 11 Plan 02, DIAG-01, DIAG-02).
//!
//! R fixtures (`urca::ur.df`, `tseries::kpss.test`) are generated by
//! `validation/reference/r/adf_kpss.R` into
//! `tests/data/r_reference/adf_kpss_r.json`.
//! Python fixtures (`statsmodels.tsa.stattools.adfuller`,
//! `statsmodels.tsa.adfvalues.mackinnonp`/`mackinnoncrit`) are generated by
//! `validation/reference/python/adf_statsmodels.py` into
//! `tests/data/r_reference/adf_statsmodels.json`.

use std::fs;
use std::path::PathBuf;

use anofox_forecast::validation::{
    adf_test, adf_test_with_options, kpss_p_value, kpss_test, mackinnon_critical_values,
    mackinnon_p_value, AdfLagSelection, AdfOptions, AdfRegression,
};
use rand::rngs::StdRng;
use rand::{Rng, SeedableRng};
use serde_json::Value;

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("data")
        .join("r_reference")
}

fn load_fixture(name: &str) -> Value {
    let path = fixtures_dir().join(format!("{}.json", name));
    let raw =
        fs::read_to_string(&path).unwrap_or_else(|_| panic!("missing fixture: {}", path.display()));
    serde_json::from_str(&raw)
        .unwrap_or_else(|e| panic!("malformed fixture {}: {}", path.display(), e))
}

fn regression_from_key(key: &str) -> AdfRegression {
    match key {
        "none" => AdfRegression::NoConstant,
        "drift" => AdfRegression::Constant,
        "trend" => AdfRegression::ConstantTrend,
        other => panic!("unknown urca type key: {}", other),
    }
}

/// `urca::ur.df(y, type, lags)@teststat[1, 1]` — the first row's first
/// column is always the ADF (`tau`) statistic, regardless of type.
fn urca_tau1(teststat: &Value) -> f64 {
    match teststat {
        Value::Number(n) => n.as_f64().unwrap(),
        Value::Array(arr) => arr[0].as_f64().unwrap(),
        other => panic!("unexpected teststat shape: {:?}", other),
    }
}

/// Parse a fixture number, accepting the non-finite sentinels used by both
/// generators ("Inf"/"-Inf"/"NaN", matching jsonlite's convention — see
/// `validation/reference/r/common.R` in the sibling duckdb repo).
fn parse_f64(v: &Value) -> f64 {
    match v {
        Value::Number(n) => n.as_f64().unwrap(),
        Value::String(s) => match s.as_str() {
            "Inf" => f64::INFINITY,
            "-Inf" => f64::NEG_INFINITY,
            "NaN" => f64::NAN,
            other => panic!("unexpected non-finite sentinel: {}", other),
        },
        other => panic!("unexpected numeric shape: {:?}", other),
    }
}

fn regression_from_sm_key(key: &str) -> AdfRegression {
    match key {
        "n" => AdfRegression::NoConstant,
        "c" => AdfRegression::Constant,
        "ct" => AdfRegression::ConstantTrend,
        other => panic!("unknown statsmodels regression key: {}", other),
    }
}

fn series_from_r_fixture(name: &str) -> Vec<f64> {
    load_fixture("adf_kpss_r")["series"][name]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_f64().unwrap())
        .collect()
}

/// Simple Box-Muller standard normal generator (no new dependency; same
/// approach already used in `src/forecastability/gcmi.rs`).
fn standard_normal(rng: &mut StdRng) -> f64 {
    let u1: f64 = rng.gen_range(f64::EPSILON..1.0);
    let u2: f64 = rng.gen_range(0.0..1.0);
    (-2.0 * u1.ln()).sqrt() * (2.0 * std::f64::consts::PI * u2).cos()
}

fn random_walk(rng: &mut StdRng, n: usize) -> Vec<f64> {
    let mut y = vec![0.0; n];
    let mut acc = 0.0;
    for v in y.iter_mut() {
        acc += standard_normal(rng);
        *v = acc;
    }
    y
}

/// IMA(1,1) with theta = -0.5: cumulative sum of an MA(1) process
/// `e_t + theta * e_{t-1}` (matches R's `arima.sim(list(ma = -0.5))` model).
fn ima_series(rng: &mut StdRng, n: usize) -> Vec<f64> {
    const THETA: f64 = -0.5;
    let mut e_prev = standard_normal(rng);
    let mut acc = 0.0;
    let mut y = vec![0.0; n];
    for v in y.iter_mut().take(n) {
        let e = standard_normal(rng);
        let ma = e + THETA * e_prev;
        acc += ma;
        *v = acc;
        e_prev = e;
    }
    y
}

#[test]
fn adf_fixed_lag_matches_urca() {
    let fixture = load_fixture("adf_kpss_r");
    let series_obj = fixture["series"].as_object().unwrap();
    let adf_fixed = fixture["adf_fixed_lag"].as_object().unwrap();

    let mut checked = 0usize;
    for (series_name, series_val) in series_obj {
        let series: Vec<f64> = series_val
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_f64().unwrap())
            .collect();

        let urdf_types = adf_fixed[series_name].as_object().unwrap();
        for (type_key, lag_map) in urdf_types {
            let regression = regression_from_key(type_key);
            let lag_map = lag_map.as_object().unwrap();
            for (lag_key, block) in lag_map {
                let lag: usize = lag_key.trim_start_matches("lag").parse().unwrap();
                let expected = urca_tau1(&block["teststat"]);

                let options = AdfOptions::default()
                    .with_regression(regression)
                    .with_max_lags(lag)
                    .with_lag_selection(AdfLagSelection::Fixed);
                let result = adf_test_with_options(&series, &options);

                assert!(
                    (result.statistic - expected).abs() <= 1e-8,
                    "series={} type={} lag={}: crate={} urca={} diff={}",
                    series_name,
                    type_key,
                    lag,
                    result.statistic,
                    expected,
                    (result.statistic - expected).abs()
                );
                checked += 1;
            }
        }
    }
    assert!(checked > 0, "no fixture cases were checked");
}

#[test]
fn adf_fixed_lag_matches_statsmodels() {
    let fixture = load_fixture("adf_statsmodels");
    let adf_fixed = fixture["adf_fixed_lag"].as_object().unwrap();

    let mut checked = 0usize;
    for (series_name, reg_map) in adf_fixed {
        let series = series_from_r_fixture(series_name);
        for (reg_key, lag_map) in reg_map.as_object().unwrap() {
            let regression = regression_from_sm_key(reg_key);
            for (lag_key, block) in lag_map.as_object().unwrap() {
                let lag: usize = lag_key.trim_start_matches("lag").parse().unwrap();
                let expected = block["statistic"].as_f64().unwrap();

                let options = AdfOptions::default()
                    .with_regression(regression)
                    .with_max_lags(lag)
                    .with_lag_selection(AdfLagSelection::Fixed);
                let result = adf_test_with_options(&series, &options);

                assert!(
                    (result.statistic - expected).abs() <= 1e-8,
                    "series={} reg={} lag={}: crate={} statsmodels={}",
                    series_name,
                    reg_key,
                    lag,
                    result.statistic,
                    expected
                );
                checked += 1;
            }
        }
    }
    assert!(checked > 0, "no fixture cases were checked");
}

#[test]
fn adf_autolag_matches_statsmodels() {
    let fixture = load_fixture("adf_statsmodels");
    let adf_autolag = fixture["adf_autolag"].as_object().unwrap();

    let method_map = [
        ("aic", AdfLagSelection::Aic),
        ("bic", AdfLagSelection::Bic),
        ("t_stat", AdfLagSelection::TStat),
    ];

    let mut checked = 0usize;
    for (series_name, reg_map) in adf_autolag {
        let series = series_from_r_fixture(series_name);
        let n = series.len();
        let max_lags = ((n - 1) as f64).powf(1.0 / 3.0).floor() as usize;

        for (reg_key, method_block) in reg_map.as_object().unwrap() {
            if reg_key == "maxlag" {
                continue;
            }
            let regression = regression_from_sm_key(reg_key);
            for (method_key, selection) in &method_map {
                let block = &method_block[method_key];
                let expected_lag = block["usedlag"].as_u64().unwrap() as usize;
                let expected_stat = block["statistic"].as_f64().unwrap();
                let expected_p = block["pvalue"].as_f64().unwrap();
                let expected_cv1 = block["critvalues"]["1%"].as_f64().unwrap();
                let expected_cv5 = block["critvalues"]["5%"].as_f64().unwrap();
                let expected_cv10 = block["critvalues"]["10%"].as_f64().unwrap();

                let options = AdfOptions::default()
                    .with_regression(regression)
                    .with_max_lags(max_lags)
                    .with_lag_selection(*selection);
                let result = adf_test_with_options(&series, &options);

                assert_eq!(
                    result.lags, expected_lag,
                    "series={} reg={} method={}: lag mismatch crate={} statsmodels={}",
                    series_name, reg_key, method_key, result.lags, expected_lag
                );
                assert!(
                    (result.statistic - expected_stat).abs() <= 1e-8,
                    "series={} reg={} method={}: statistic crate={} statsmodels={}",
                    series_name,
                    reg_key,
                    method_key,
                    result.statistic,
                    expected_stat
                );
                assert!(
                    (result.p_value - expected_p).abs() <= 1e-8,
                    "series={} reg={} method={}: p_value crate={} statsmodels={}",
                    series_name,
                    reg_key,
                    method_key,
                    result.p_value,
                    expected_p
                );
                assert!((result.critical_values.cv_1pct - expected_cv1).abs() <= 1e-10);
                assert!((result.critical_values.cv_5pct - expected_cv5).abs() <= 1e-10);
                assert!((result.critical_values.cv_10pct - expected_cv10).abs() <= 1e-10);
                checked += 1;
            }
        }
    }
    assert!(checked > 0, "no fixture cases were checked");
}

#[test]
fn mackinnon_tables_match_statsmodels() {
    let fixture = load_fixture("adf_statsmodels");
    let tables = &fixture["mackinnon_tables"];

    for reg_key in ["n", "c", "ct"] {
        let regression = regression_from_sm_key(reg_key);
        let max_stat = parse_f64(&tables["tau_max"][reg_key]);
        let min_stat = parse_f64(&tables["tau_min"][reg_key]);

        // p = 0.0 strictly below tau_min (every regression's tau_min is finite).
        let p_below_min = mackinnon_p_value(min_stat - 1.0, regression);
        assert_eq!(
            p_below_min, 0.0,
            "reg={}: p below tau_min should be 0.0",
            reg_key
        );

        if max_stat.is_finite() {
            let p_above_max = mackinnon_p_value(max_stat + 1.0, regression);
            assert_eq!(
                p_above_max, 1.0,
                "reg={}: p above tau_max should be 1.0",
                reg_key
            );
        } else {
            // "n" has tau_max = Inf, so the `statistic > max_stat` shortcut
            // never fires; p still saturates to 1.0 via the largep
            // polynomial's normal-CDF tail for large statistics — verified
            // to match statsmodels' own mackinnonp(1e6, 'n', N=1) == 1.0.
            let p_large = mackinnon_p_value(1.0e6, regression);
            assert_eq!(p_large, 1.0, "reg={}: p at a very large statistic", reg_key);
        }
    }
}

#[test]
fn mackinnon_p_value_grid() {
    let fixture = load_fixture("adf_statsmodels");
    let grid = fixture["mackinnonp_grid"].as_object().unwrap();

    let mut checked = 0usize;
    for (reg_key, points) in grid {
        let regression = regression_from_sm_key(reg_key);
        for point in points.as_array().unwrap() {
            let stat = point["statistic"].as_f64().unwrap();
            let expected = point["pvalue"].as_f64().unwrap();
            let actual = mackinnon_p_value(stat, regression);
            assert!(
                (actual - expected).abs() <= 1e-10,
                "reg={} stat={}: crate={} statsmodels={}",
                reg_key,
                stat,
                actual,
                expected
            );
            checked += 1;
        }
    }
    assert!(checked > 0, "no grid points were checked");
}

#[test]
fn mackinnon_critical_values_grid() {
    let fixture = load_fixture("adf_statsmodels");
    let grid = fixture["mackinnoncrit_grid"].as_object().unwrap();

    let mut checked = 0usize;
    for (reg_key, rows) in grid {
        let regression = regression_from_sm_key(reg_key);
        for row in rows.as_array().unwrap() {
            let nobs = row["nobs"].as_u64().unwrap() as usize;
            let expected_cv1 = row["cv_1pct"].as_f64().unwrap();
            let expected_cv5 = row["cv_5pct"].as_f64().unwrap();
            let expected_cv10 = row["cv_10pct"].as_f64().unwrap();

            let cv = mackinnon_critical_values(regression, nobs);
            assert!(
                (cv.cv_1pct - expected_cv1).abs() <= 1e-10,
                "reg={} nobs={}",
                reg_key,
                nobs
            );
            assert!(
                (cv.cv_5pct - expected_cv5).abs() <= 1e-10,
                "reg={} nobs={}",
                reg_key,
                nobs
            );
            assert!(
                (cv.cv_10pct - expected_cv10).abs() <= 1e-10,
                "reg={} nobs={}",
                reg_key,
                nobs
            );
            checked += 1;
        }
    }
    assert!(checked > 0, "no grid rows were checked");
}

#[test]
fn adf_default_is_constant_aic() {
    let series = series_from_r_fixture("rw");

    let via_default = adf_test(&series, None);
    let via_options = adf_test_with_options(&series, &AdfOptions::default());
    assert_eq!(via_default.statistic, via_options.statistic);
    assert_eq!(via_default.p_value, via_options.p_value);
    assert_eq!(via_default.lags, via_options.lags);
    assert_eq!(via_default.is_stationary, via_options.is_stationary);
    assert_eq!(
        via_default.critical_values.cv_1pct,
        via_options.critical_values.cv_1pct
    );
    assert_eq!(
        via_default.critical_values.cv_5pct,
        via_options.critical_values.cv_5pct
    );
    assert_eq!(
        via_default.critical_values.cv_10pct,
        via_options.critical_values.cv_10pct
    );

    let via_fixed_max = adf_test(&series, Some(3));
    let via_options_3 = adf_test_with_options(&series, &AdfOptions::default().with_max_lags(3));
    assert_eq!(via_fixed_max.statistic, via_options_3.statistic);
    assert_eq!(via_fixed_max.lags, via_options_3.lags);
}

#[test]
fn adf_mc_fixture_matches_statsmodels() {
    let r_fixture = load_fixture("adf_kpss_r");
    let sm_fixture = load_fixture("adf_statsmodels");

    let mc_options = AdfOptions::default()
        .with_regression(AdfRegression::Constant)
        .with_max_lags(5)
        .with_lag_selection(AdfLagSelection::Aic);

    for (kind, r_key, sm_key) in [
        ("random_walk", "random_walk_series", "random_walk"),
        ("ima", "ima_theta_neg_0_5_series", "ima_theta_neg_0_5"),
    ] {
        let raw_series = r_fixture["monte_carlo"][r_key].as_array().unwrap();
        let expected_rows = sm_fixture["monte_carlo"][sm_key].as_array().unwrap();
        let urca_rows = r_fixture["monte_carlo"][match kind {
            "random_walk" => "random_walk",
            _ => "ima_theta_neg_0_5",
        }]
        .as_array()
        .unwrap();

        let mut crate_rejections = 0;
        let mut sm_rejections = 0;
        let mut urca_rejections = 0;

        for i in 0..raw_series.len() {
            let series: Vec<f64> = raw_series[i]
                .as_array()
                .unwrap()
                .iter()
                .map(|v| v.as_f64().unwrap())
                .collect();
            let result = adf_test_with_options(&series, &mc_options);

            let expected_stat = expected_rows[i]["statistic"].as_f64().unwrap();
            let expected_lag = expected_rows[i]["usedlag"].as_u64().unwrap() as usize;
            let expected_p = expected_rows[i]["pvalue"].as_f64().unwrap();

            assert!(
                (result.statistic - expected_stat).abs() <= 1e-8,
                "{} series {}: statistic crate={} statsmodels={}",
                kind,
                i,
                result.statistic,
                expected_stat
            );
            assert_eq!(
                result.lags, expected_lag,
                "{} series {}: lag mismatch",
                kind, i
            );
            assert!(
                (result.p_value - expected_p).abs() <= 1e-8,
                "{} series {}: p_value crate={} statsmodels={}",
                kind,
                i,
                result.p_value,
                expected_p
            );

            if result.p_value < 0.05 {
                crate_rejections += 1;
            }
            if expected_rows[i]["reject_5pct"].as_bool().unwrap() {
                sm_rejections += 1;
            }
            if urca_rows[i]["reject_5pct"].as_bool().unwrap() {
                urca_rejections += 1;
            }
        }

        println!(
            "{} rejection rates @5%: crate={}/{} statsmodels={}/{} urca={}/{}",
            kind,
            crate_rejections,
            raw_series.len(),
            sm_rejections,
            raw_series.len(),
            urca_rejections,
            raw_series.len()
        );
        // The crate's fixed selection matches statsmodels exactly, so its
        // rejection count must match statsmodels' exactly.
        assert_eq!(
            crate_rejections, sm_rejections,
            "{}: rejection count mismatch vs statsmodels",
            kind
        );
    }
}

#[test]
fn adf_size_reduced() {
    let mut rng = StdRng::seed_from_u64(20261009);
    let mut rejections = 0;
    const REPS: usize = 300;
    for _ in 0..REPS {
        let series = random_walk(&mut rng, 200);
        let result = adf_test(&series, None);
        if result.p_value < 0.05 {
            rejections += 1;
        }
    }
    let rate = rejections as f64 / REPS as f64;
    assert!(
        (0.02..=0.09).contains(&rate),
        "random-walk size at 5% should be in [0.02, 0.09], got {} ({}/{})",
        rate,
        rejections,
        REPS
    );
}

#[test]
#[ignore = "monte-carlo: cargo test --test adf_kpss_reference -- --ignored adf_size_monte_carlo --nocapture"]
fn adf_size_monte_carlo() {
    let mut rng = StdRng::seed_from_u64(20261009);
    const REPS: usize = 2000;

    let mut rw_rejections = 0;
    for _ in 0..REPS {
        let series = random_walk(&mut rng, 200);
        let result = adf_test(&series, None);
        if result.p_value < 0.05 {
            rw_rejections += 1;
        }
    }
    let rw_size = rw_rejections as f64 / REPS as f64;

    let mut ima_rejections = 0;
    for _ in 0..REPS {
        let series = ima_series(&mut rng, 200);
        let result = adf_test(&series, None);
        if result.p_value < 0.05 {
            ima_rejections += 1;
        }
    }
    let ima_rate = ima_rejections as f64 / REPS as f64;

    println!(
        "Monte-Carlo (n={}): random-walk size @5% = {:.4} ({}/{}); IMA(1,1) theta=-0.5 rejection @5% = {:.4} ({}/{})",
        REPS, rw_size, rw_rejections, REPS, ima_rate, ima_rejections, REPS
    );

    assert!(
        (0.035..=0.075).contains(&rw_size),
        "random-walk size at 5% should be in [0.035, 0.075], got {}",
        rw_size
    );
    assert!(
        ima_rate <= 0.15,
        "IMA(1,1) theta=-0.5 rejection at 5% should be <= 0.15, got {}",
        ima_rate
    );
}

#[test]
fn kpss_matches_tseries() {
    let fixture = load_fixture("adf_kpss_r");
    let kpss_obj = fixture["kpss"].as_object().unwrap();

    let mut checked = 0usize;
    for (series_name, block) in kpss_obj {
        // Every "kpss" entry (main battery + the extra ar_phi_* series that
        // exercise all five tseries p-value regions) carries its own raw
        // "values", independent of the top-level "series" block.
        let series: Vec<f64> = block["values"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_f64().unwrap())
            .collect();

        let expected_stat = block["statistic"].as_f64().unwrap();
        let expected_lag = block["lag"].as_f64().unwrap() as usize;
        let expected_p = block["p_value"].as_f64().unwrap();

        let result = kpss_test(&series, None);

        assert!(
            (result.statistic - expected_stat).abs() <= 1e-8,
            "series={}: statistic crate={} tseries={}",
            series_name,
            result.statistic,
            expected_stat
        );
        assert_eq!(
            result.lags, expected_lag,
            "series={}: lag mismatch",
            series_name
        );
        assert!(
            (result.p_value - expected_p).abs() <= 1e-10,
            "series={}: p_value crate={} tseries={}",
            series_name,
            result.p_value,
            expected_p
        );
        assert!(
            (0.01..=0.10).contains(&result.p_value),
            "series={}: p_value {} outside [0.01, 0.10]",
            series_name,
            result.p_value
        );
        checked += 1;
    }
    assert!(checked > 0, "no fixture series were checked");
}

#[test]
fn kpss_p_value_bounded_monotone() {
    let mut prev: Option<f64> = None;
    let mut stat = 0.0_f64;
    while stat <= 2.0 {
        let p = kpss_p_value(stat);
        assert!(
            (0.01..=0.10).contains(&p),
            "stat={}: p={} outside [0.01, 0.10]",
            stat,
            p
        );
        if let Some(prev_p) = prev {
            assert!(
                p <= prev_p + 1e-12,
                "stat={}: p={} should be <= previous p={} (non-increasing)",
                stat,
                p,
                prev_p
            );
        }
        prev = Some(p);
        stat += 0.01;
    }

    assert_eq!(kpss_p_value(0.0), 0.10);
    assert_eq!(kpss_p_value(0.347), 0.10);
    assert_eq!(kpss_p_value(0.739), 0.01);
    assert_eq!(kpss_p_value(2.0), 0.01);
    assert_eq!(kpss_p_value(0.574), 0.025);
}
