//! Reference-fixture tests for the augmented ADF / KPSS implementation
//! (Phase 11 Plan 02, DIAG-01, DIAG-02).
//!
//! R fixtures (`urca::ur.df`, `tseries::kpss.test`) are generated by
//! `validation/reference/r/adf_kpss.R` into
//! `tests/data/r_reference/adf_kpss_r.json`.
//! Python fixtures (`statsmodels.tsa.stattools.adfuller`,
//! `statsmodels.tsa.adfvalues.mackinnonp`/`mackinnoncrit`) are generated by
//! `validation/reference/python/adf_statsmodels.py` into
//! `tests/data/r_reference/adf_statsmodels.json`.

use std::fs;
use std::path::PathBuf;

use anofox_forecast::validation::{
    adf_test_with_options, AdfLagSelection, AdfOptions, AdfRegression,
};
use serde_json::Value;

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("data")
        .join("r_reference")
}

fn load_fixture(name: &str) -> Value {
    let path = fixtures_dir().join(format!("{}.json", name));
    let raw =
        fs::read_to_string(&path).unwrap_or_else(|_| panic!("missing fixture: {}", path.display()));
    serde_json::from_str(&raw)
        .unwrap_or_else(|e| panic!("malformed fixture {}: {}", path.display(), e))
}

fn regression_from_key(key: &str) -> AdfRegression {
    match key {
        "none" => AdfRegression::NoConstant,
        "drift" => AdfRegression::Constant,
        "trend" => AdfRegression::ConstantTrend,
        other => panic!("unknown urca type key: {}", other),
    }
}

/// `urca::ur.df(y, type, lags)@teststat[1, 1]` — the first row's first
/// column is always the ADF (`tau`) statistic, regardless of type.
fn urca_tau1(teststat: &Value) -> f64 {
    match teststat {
        Value::Number(n) => n.as_f64().unwrap(),
        Value::Array(arr) => arr[0].as_f64().unwrap(),
        other => panic!("unexpected teststat shape: {:?}", other),
    }
}

#[test]
fn adf_fixed_lag_matches_urca() {
    let fixture = load_fixture("adf_kpss_r");
    let series_obj = fixture["series"].as_object().unwrap();
    let adf_fixed = fixture["adf_fixed_lag"].as_object().unwrap();

    let mut checked = 0usize;
    for (series_name, series_val) in series_obj {
        let series: Vec<f64> = series_val
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_f64().unwrap())
            .collect();

        let urdf_types = adf_fixed[series_name].as_object().unwrap();
        for (type_key, lag_map) in urdf_types {
            let regression = regression_from_key(type_key);
            let lag_map = lag_map.as_object().unwrap();
            for (lag_key, block) in lag_map {
                let lag: usize = lag_key.trim_start_matches("lag").parse().unwrap();
                let expected = urca_tau1(&block["teststat"]);

                let options = AdfOptions::default()
                    .with_regression(regression)
                    .with_max_lags(lag)
                    .with_lag_selection(AdfLagSelection::Fixed);
                let result = adf_test_with_options(&series, &options);

                assert!(
                    (result.statistic - expected).abs() <= 1e-8,
                    "series={} type={} lag={}: crate={} urca={} diff={}",
                    series_name,
                    type_key,
                    lag,
                    result.statistic,
                    expected,
                    (result.statistic - expected).abs()
                );
                checked += 1;
            }
        }
    }
    assert!(checked > 0, "no fixture cases were checked");
}
