//! R `forecast::auto.arima` / `ndiffs` / `nsdiffs` parity tests
//! (branch fix/auto-arima-order-selection, phase 11-04/11-05).
//!
//! Fixtures are generated by `validation/reference/r/auto_arima.R`
//! (R `forecast` 9.0.2 + `urca`) and stored at
//! `tests/data/r_reference/auto_arima_r.json`. This test loads that
//! fixture and asserts the crate's `ndiffs_kpss`/`nsdiffs_seas` and
//! `AutoARIMA`'s order selection against R's own computed values.

use anofox_forecast::core::TimeSeries;
use anofox_forecast::models::arima::{ndiffs_kpss, AutoARIMA};
use anofox_forecast::models::Forecaster;
use chrono::{Duration, TimeZone, Utc};
use serde_json::Value;

fn make_timestamps(n: usize) -> Vec<chrono::DateTime<Utc>> {
    (0..n)
        .map(|i| Utc.with_ymd_and_hms(2020, 1, 1, 0, 0, 0).unwrap() + Duration::days(i as i64))
        .collect()
}

fn load_fixture() -> Value {
    let path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("data")
        .join("r_reference")
        .join("auto_arima_r.json");
    let raw = std::fs::read_to_string(&path)
        .unwrap_or_else(|_| panic!("missing fixture: {}", path.display()));
    serde_json::from_str(&raw)
        .unwrap_or_else(|e| panic!("malformed fixture {}: {}", path.display(), e))
}

fn as_f64_vec(v: &Value) -> Vec<f64> {
    v.as_array()
        .unwrap()
        .iter()
        .map(|x| x.as_f64().unwrap())
        .collect()
}

fn nonseasonal_series(fixture: &Value) -> Vec<(String, usize, Vec<f64>)> {
    let mut out = Vec::new();
    for family in ["rw", "ar1"] {
        let entries = fixture[family].as_array().unwrap();
        for (i, entry) in entries.iter().enumerate() {
            out.push((format!("{family}[{i}]"), i, as_f64_vec(&entry["values"])));
        }
    }
    out
}

/// `ndiffs_kpss` must equal R `forecast::ndiffs` for all 100 non-seasonal
/// fixture series (50 random walks + 50 AR(0.7)).
#[test]
fn ndiffs_matches_r() {
    let fixture = load_fixture();
    let mut checked = 0usize;

    for family in ["rw", "ar1"] {
        let entries = fixture[family].as_array().unwrap();
        for (i, entry) in entries.iter().enumerate() {
            let values = as_f64_vec(&entry["values"]);
            let expected_d = entry["ndiffs"].as_u64().unwrap() as usize;

            let d = ndiffs_kpss(&values, 0.05, 2);
            assert_eq!(
                d, expected_d,
                "{family}[{i}]: ndiffs_kpss={d} vs R ndiffs={expected_d}"
            );
            checked += 1;
        }
    }
    assert_eq!(checked, 100, "expected 100 non-seasonal fixture series");
}

/// `AutoARIMA::new()`'s selected `d` must equal R `auto.arima`'s selected
/// `d` for all 100 non-seasonal fixture series.
#[test]
fn auto_arima_d_matches_r() {
    let fixture = load_fixture();
    let series = nonseasonal_series(&fixture);
    let mut mismatches = Vec::new();

    for (label, idx, values) in &series {
        let family = if label.starts_with("rw") { "rw" } else { "ar1" };
        let expected_d = fixture[family][idx]["d"].as_u64().unwrap() as usize;

        let timestamps = make_timestamps(values.len());
        let ts = TimeSeries::univariate(timestamps, values.clone()).unwrap();
        let mut model = AutoARIMA::new();
        model
            .fit(&ts)
            .unwrap_or_else(|e| panic!("{label}: fit failed: {e}"));
        let order = model
            .selected_full_order()
            .unwrap_or_else(|| panic!("{label}: no selected order"));

        if order.d != expected_d {
            mismatches.push(format!("{label}: crate d={} vs R d={expected_d}", order.d));
        }
    }

    assert!(
        mismatches.is_empty(),
        "d mismatches vs R auto.arima:\n{}",
        mismatches.join("\n")
    );
}
