//! R `forecast::ets` / `ses`/`holt`/`hw` parity tests
//! (branch fix/ets-likelihood-intervals, phase 11-06/11-07/11-08).
//!
//! Fixtures are generated by `validation/reference/r/ets.R` (R `forecast`
//! 9.0.2) and stored at `tests/data/r_reference/ets_r.json`. This test loads
//! that fixture and asserts the crate's ETS likelihood/AIC/AICc/BIC/fitted
//! values/final states against R's own computed values at R's own fitted
//! parameters (no optimisation on the crate side), plus (in later plan
//! tasks) optimised-fit quality, usual-constraint compliance, and AutoETS
//! candidate-pool/selection parity.

use anofox_forecast::core::TimeSeries;
use anofox_forecast::models::exponential::{ETSSpec, ETS};
use anofox_forecast::models::Forecaster;
use chrono::{Duration, TimeZone, Utc};
use serde_json::Value;

fn make_timestamps(n: usize) -> Vec<chrono::DateTime<Utc>> {
    (0..n)
        .map(|i| Utc.with_ymd_and_hms(1949, 1, 1, 0, 0, 0).unwrap() + Duration::days(30 * i as i64))
        .collect()
}

fn load_fixture() -> Value {
    let path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("data")
        .join("r_reference")
        .join("ets_r.json");
    let raw = std::fs::read_to_string(&path)
        .unwrap_or_else(|_| panic!("missing fixture: {}", path.display()));
    serde_json::from_str(&raw)
        .unwrap_or_else(|e| panic!("malformed fixture {}: {}", path.display(), e))
}

fn as_f64_vec(v: &Value) -> Vec<f64> {
    v.as_array()
        .unwrap()
        .iter()
        .map(|x| x.as_f64().unwrap())
        .collect()
}

fn as_f64(v: &Value) -> f64 {
    v.as_f64().unwrap()
}

/// Relative-tolerance comparison with an absolute floor for near-zero
/// expected values (residuals / fitted values can legitimately be tiny).
fn assert_rel_close(actual: f64, expected: f64, tol: f64, label: &str) {
    let diff = (actual - expected).abs();
    let scale = expected.abs().max(1e-6);
    let rel = diff / scale;
    assert!(
        rel <= tol,
        "{label}: actual={actual} expected={expected} rel_diff={rel} (tol={tol})"
    );
}

/// R's `ets_fit_block()`/`ets_auto_block()` JSON entries store the model's
/// full state vector (l, b?, s1..sm) at a point in time (initial or final).
/// The crate's seasonal buffer is indexed by `t % m` (t = 0 for y_1); per
/// the planning-time derivation (confirmed numerically against this exact
/// fixture), `buffer[k] == R_seasonal_state[m - 1 - k]`, i.e. the crate
/// buffer is R's seasonal state slice *reversed*. See 11-06-PLAN.md
/// <interfaces> for the full derivation.
fn r_state_to_crate(state_names: &[String], state: &[f64]) -> (f64, f64, Vec<f64>) {
    let level = state[0];
    let has_trend = state_names.len() > 1 && state_names[1] == "b";
    let trend = if has_trend { state[1] } else { 0.0 };
    let seasonal_start = if has_trend { 2 } else { 1 };
    let mut seasonal: Vec<f64> = state[seasonal_start..].to_vec();
    seasonal.reverse();
    (level, trend, seasonal)
}

fn state_names(entry: &Value) -> Vec<String> {
    entry["state_names"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_str().unwrap().to_string())
        .collect()
}

/// ETS(M,A,M) on AirPassengers, scored at R's own fitted alpha/beta/gamma
/// and R's own initial states (no optimisation on the crate side): the
/// crate's log-likelihood/AIC/AICc/BIC must equal R's to 1e-6 relative, the
/// fitted values to 1e-8 relative, and the final level/trend/seasonals
/// (from `fitted_params()`) to 1e-8 relative.
#[test]
fn ets_loglik_at_r_params_mam() {
    let fixture = load_fixture();
    let air = as_f64_vec(&fixture["air"]);
    let entry = &fixture["air_fits"]["MAM"];

    let par = &entry["par"];
    let alpha = as_f64(&par["alpha"]);
    let beta = as_f64(&par["beta"]);
    let gamma = as_f64(&par["gamma"]);

    let names = state_names(entry);
    let initial_state = as_f64_vec(&entry["initial_state"]);
    let (level0, trend0, seasonals0) = r_state_to_crate(&names, &initial_state);

    let ts = TimeSeries::univariate(make_timestamps(air.len()), air.clone()).unwrap();

    let mut model = ETS::with_params_and_states(
        ETSSpec::mam(),
        12,
        alpha,
        Some(beta),
        Some(gamma),
        None,
        level0,
        trend0,
        seasonals0,
    );
    model.fit(&ts).unwrap();

    let expected_loglik = as_f64(&entry["loglik"]);
    let expected_aic = as_f64(&entry["aic"]);
    let expected_aicc = as_f64(&entry["aicc"]);
    let expected_bic = as_f64(&entry["bic"]);

    assert_rel_close(
        model.log_likelihood().unwrap(),
        expected_loglik,
        1e-6,
        "MAM loglik",
    );
    assert_rel_close(model.aic().unwrap(), expected_aic, 1e-6, "MAM aic");
    assert_rel_close(model.aicc().unwrap(), expected_aicc, 1e-6, "MAM aicc");
    assert_rel_close(model.bic().unwrap(), expected_bic, 1e-6, "MAM bic");

    let expected_fitted = as_f64_vec(&entry["fitted"]);
    let fitted = model.fitted_values().unwrap();
    assert_eq!(fitted.len(), expected_fitted.len(), "MAM fitted length");
    for (i, (&a, &e)) in fitted.iter().zip(expected_fitted.iter()).enumerate() {
        assert_rel_close(a, e, 1e-8, &format!("MAM fitted[{i}]"));
    }

    let expected_final = as_f64_vec(&entry["final_state"]);
    let (exp_level, exp_trend, exp_seasonals) = r_state_to_crate(&names, &expected_final);

    let fp = model.fitted_params().unwrap();
    assert_rel_close(fp.params["level"], exp_level, 1e-8, "MAM final level");
    assert_rel_close(fp.params["trend"], exp_trend, 1e-8, "MAM final trend");
    let final_seasonals = fp.seasonal.unwrap();
    assert_eq!(
        final_seasonals.len(),
        exp_seasonals.len(),
        "MAM seasonal len"
    );
    for (i, (&a, &e)) in final_seasonals.iter().zip(exp_seasonals.iter()).enumerate() {
        assert_rel_close(a, e, 1e-8, &format!("MAM final seasonal[{i}]"));
    }
}
