//! ETS prediction-interval parity vs R `forecast::ets` + Monte-Carlo
//! coverage (branch fix/ets-likelihood-intervals, plan 11-07, D-08).
//!
//! Fixtures are generated by `validation/reference/r/ets.R` (R `forecast`
//! 9.0.2) and stored at `tests/data/r_reference/ets_r.json` (shared with
//! `tests/ets_r_reference.rs`, generated once in plan 11-06). This file
//! loads that fixture and asserts the crate's `predict_with_intervals`
//! bounds against R's own `forecast.ets` 80%/95% bounds at R's own fitted
//! parameters (no optimisation on the crate side), plus Monte-Carlo
//! coverage of the intervals on simulated DGPs.
//!
//! No shared test module with `ets_r_reference.rs` by design (11-07-PLAN.md
//! `<interfaces>`); the minimal fixture-loading/R-state-conversion helpers
//! below are deliberately duplicated rather than factored into a shared
//! module.

use anofox_forecast::core::TimeSeries;
use anofox_forecast::models::exponential::{ETSSpec, ETS};
use anofox_forecast::models::Forecaster;
use chrono::{Duration, TimeZone, Utc};
use serde_json::Value;

fn make_timestamps(n: usize) -> Vec<chrono::DateTime<Utc>> {
    (0..n)
        .map(|i| Utc.with_ymd_and_hms(1949, 1, 1, 0, 0, 0).unwrap() + Duration::days(30 * i as i64))
        .collect()
}

fn load_fixture() -> Value {
    let path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("data")
        .join("r_reference")
        .join("ets_r.json");
    let raw = std::fs::read_to_string(&path)
        .unwrap_or_else(|_| panic!("missing fixture: {}", path.display()));
    serde_json::from_str(&raw)
        .unwrap_or_else(|e| panic!("malformed fixture {}: {}", path.display(), e))
}

/// jsonlite's `auto_unbox = TRUE` collapses length-1 R vectors to a bare
/// scalar instead of a 1-element array (hits non-trend, non-seasonal models
/// like ANN, whose `initial_state`/`final_state`/`state_names` is just the
/// single level state `l`), so this accepts both shapes.
fn as_f64_vec(v: &Value) -> Vec<f64> {
    match v.as_array() {
        Some(arr) => arr.iter().map(|x| x.as_f64().unwrap()).collect(),
        None => vec![v.as_f64().unwrap()],
    }
}

fn as_f64(v: &Value) -> f64 {
    v.as_f64().unwrap()
}

fn state_names(entry: &Value) -> Vec<String> {
    let v = &entry["state_names"];
    match v.as_array() {
        Some(arr) => arr
            .iter()
            .map(|x| x.as_str().unwrap().to_string())
            .collect(),
        None => vec![v.as_str().unwrap().to_string()],
    }
}

/// See `tests/ets_r_reference.rs`'s identical helper / 11-06-PLAN.md
/// `<interfaces>` for the derivation: the crate's seasonal buffer is R's
/// seasonal state slice reversed.
fn r_state_to_crate(names: &[String], state: &[f64]) -> (f64, f64, Vec<f64>) {
    let level = state[0];
    let has_trend = names.len() > 1 && names[1] == "b";
    let trend = if has_trend { state[1] } else { 0.0 };
    let seasonal_start = if has_trend { 2 } else { 1 };
    let mut seasonal: Vec<f64> = state[seasonal_start..].to_vec();
    seasonal.reverse();
    (level, trend, seasonal)
}

/// Relative-tolerance comparison with an absolute floor for near-zero
/// expected values.
fn assert_rel_close(actual: f64, expected: f64, tol: f64, label: &str) {
    let diff = (actual - expected).abs();
    let scale = expected.abs().max(1e-6);
    let rel = diff / scale;
    assert!(
        rel <= tol,
        "{label}: actual={actual} expected={expected} rel_diff={rel} (tol={tol})"
    );
}

struct FixtureFit<'a> {
    series: &'a str,
    model: &'a str,
    spec: ETSSpec,
    period: usize,
}

fn check_class1_or_2_model(fit: &FixtureFit, tol: f64) {
    let fixture = load_fixture();
    let series = as_f64_vec(&fixture[fit.series]);
    let entry = &fixture[format!("{}_fits", fit.series)][fit.model];

    let par = &entry["par"];
    let alpha = as_f64(&par["alpha"]);
    let beta = par.get("beta").map(as_f64);
    let gamma = par.get("gamma").map(as_f64);
    let phi = par.get("phi").map(as_f64);

    let names = state_names(entry);
    let initial_state = as_f64_vec(&entry["initial_state"]);
    let (level0, trend0, seasonals0) = r_state_to_crate(&names, &initial_state);

    let ts = TimeSeries::univariate(make_timestamps(series.len()), series.clone()).unwrap();

    let mut model = ETS::with_params_and_states(
        fit.spec, fit.period, alpha, beta, gamma, phi, level0, trend0, seasonals0,
    );
    model.fit(&ts).unwrap();

    let expected = &entry["forecast"];
    let expected_mean = as_f64_vec(&expected["mean"]);
    let horizon = expected_mean.len();

    for (level, suffix) in [(0.80, "80"), (0.95, "95")] {
        let forecast = model.predict_with_intervals(horizon, level).unwrap();
        let lower = forecast
            .lower_series(0)
            .unwrap_or_else(|_| panic!("{}: missing lower bound", fit.model));
        let upper = forecast
            .upper_series(0)
            .unwrap_or_else(|_| panic!("{}: missing upper bound", fit.model));
        let expected_lower = as_f64_vec(&expected[format!("lower_{suffix}")]);
        let expected_upper = as_f64_vec(&expected[format!("upper_{suffix}")]);

        for h in 0..horizon {
            assert_rel_close(
                lower[h],
                expected_lower[h],
                tol,
                &format!("{} lower_{} h={}", fit.model, suffix, h + 1),
            );
            assert_rel_close(
                upper[h],
                expected_upper[h],
                tol,
                &format!("{} upper_{} h={}", fit.model, suffix, h + 1),
            );
        }
    }
}

/// Class 1 (additive error, trend N/A/Ad, season N/A): ANN/AAN/AAdN on
/// `pos`, ANA/AAA/AAdA on `air` -- every model's Hyndman et al. (2008)
/// analytic 80%/95% bounds at R's own fitted parameters must equal R's own
/// `forecast.ets` bounds to 1e-6 relative, for h = 1..24.
#[test]
fn ets_class1_intervals_match_r() {
    let cases = [
        FixtureFit {
            series: "pos",
            model: "ANN",
            spec: ETSSpec::ann(),
            period: 1,
        },
        FixtureFit {
            series: "pos",
            model: "AAN",
            spec: ETSSpec::aan(),
            period: 1,
        },
        FixtureFit {
            series: "pos",
            model: "AAdN",
            spec: ETSSpec::aadn(),
            period: 1,
        },
        FixtureFit {
            series: "air",
            model: "ANA",
            spec: ETSSpec::ana(),
            period: 12,
        },
        FixtureFit {
            series: "air",
            model: "AAA",
            spec: ETSSpec::aaa(),
            period: 12,
        },
        FixtureFit {
            series: "air",
            model: "AAdA",
            spec: ETSSpec::aada(),
            period: 12,
        },
    ];

    for case in &cases {
        check_class1_or_2_model(case, 1e-6);
    }
}
