//! GARCH(1,1) reference diagnostics and shipped-outcome tests (Phase 11, UPST-05).
//!
//! Fixture generated by `validation/reference/python/garch_reference.py` (statsforecast
//! 2.0.3, numpy 2.3.5), stored at `tests/data/r_reference/garch_reference.json`. It contains
//! two series simulated from a TRUE GARCH(1,1) DGP (omega=0.1, alpha=0.1, beta=0.8, zero-mean
//! and a mu=5 shifted copy) plus the real `heteroscedastic`/`ar1` validation series, and
//! statsforecast's own fit/forecast/interval numbers on all four.
//!
//! `garch_interval_coverage_on_true_dgp` is the shipped-outcome test: it simulates 1000
//! continuations from the TRUE DGP parameters (not the crate's own fit) and checks the
//! crate's `predict_with_intervals` bounds against them. This is deliberately NOT a
//! statsforecast-parity test — see the findings table in 11-09-SUMMARY.md for why
//! statsforecast's own GARCH interval formula is not used as ground truth here (H5).

use std::fs;
use std::path::PathBuf;

use anofox_forecast::core::TimeSeries;
use anofox_forecast::models::garch::GARCH;
use anofox_forecast::models::Forecaster;
use chrono::{Duration, TimeZone, Utc};
use rand::{rngs::StdRng, Rng, SeedableRng};
use serde::Deserialize;

#[derive(Debug, Deserialize)]
#[allow(dead_code)]
struct TrueDgp {
    omega: f64,
    alpha: f64,
    beta: f64,
    n: usize,
    burn_in: usize,
    note: String,
}

#[derive(Debug, Deserialize)]
#[allow(dead_code)]
struct SfSeriesResult {
    series_type: String,
    n: usize,
    coeff_omega: f64,
    coeff_alpha: f64,
    coeff_beta: f64,
    sigma2_forecast: Vec<f64>,
    mean_forecast: Vec<f64>,
    lo_80: Vec<f64>,
    hi_80: Vec<f64>,
    lo_95: Vec<f64>,
    hi_95: Vec<f64>,
}

#[derive(Debug, Deserialize)]
#[allow(dead_code)]
struct Fixture {
    provenance: serde_json::Value,
    true_dgp: TrueDgp,
    series_values: std::collections::HashMap<String, Vec<f64>>,
    statsforecast: std::collections::HashMap<String, SfSeriesResult>,
}

fn load_fixture() -> Fixture {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("data")
        .join("r_reference")
        .join("garch_reference.json");
    let raw = fs::read_to_string(&path).unwrap_or_else(|_| {
        panic!(
            "missing fixture: {}; run validation/reference/python/garch_reference.py",
            path.display()
        )
    });
    serde_json::from_str(&raw)
        .unwrap_or_else(|e| panic!("malformed fixture {}: {}", path.display(), e))
}

fn make_timestamps(n: usize) -> Vec<chrono::DateTime<Utc>> {
    let base = Utc.with_ymd_and_hms(2020, 1, 1, 0, 0, 0).unwrap();
    (0..n).map(|i| base + Duration::hours(i as i64)).collect()
}

fn make_series(values: &[f64]) -> TimeSeries {
    TimeSeries::univariate(make_timestamps(values.len()), values.to_vec()).unwrap()
}

fn fit_crate_garch(values: &[f64]) -> GARCH {
    let ts = make_series(values);
    let mut model = GARCH::garch_1_1();
    model.fit(&ts).unwrap();
    model
}

/// Closed-form GARCH(1,1) multi-step variance recursion at the model's own fitted
/// parameters, using the model's own last-p raw values and last-q sigma^2 state
/// (reconstructed here from public accessors + the input series, since the internal
/// `y_vals`/`sigma2_vals` forecasting state is private).
fn closed_form_variance_forecast(model: &GARCH, values: &[f64], horizon: usize) -> Vec<f64> {
    let omega = model.omega();
    let alpha = model.alpha_params()[0];
    let beta = model.beta_params()[0];
    let cond_var = model.conditional_variance().unwrap();

    let last_y = values[values.len() - 1];
    let last_sigma2 = cond_var[cond_var.len() - 1];

    let mut out = Vec::with_capacity(horizon);
    // h = 1: uses the last observed y and sigma2.
    let mut sigma2_h = omega + alpha * last_y * last_y + beta * last_sigma2;
    out.push(sigma2_h);
    // h >= 2: sigma2_{n+h} = omega + (alpha + beta) * sigma2_{n+h-1}.
    for _ in 1..horizon {
        sigma2_h = omega + (alpha + beta) * sigma2_h;
        out.push(sigma2_h);
    }
    out
}

#[test]
fn garch_parameter_recovery() {
    let fixture = load_fixture();
    let true_dgp = &fixture.true_dgp;
    let values = &fixture.series_values["simulated_zero_mean"];
    let sf = &fixture.statsforecast["simulated_zero_mean"];

    let model = fit_crate_garch(values);

    println!(
        "garch_parameter_recovery: true=(omega={:.4}, alpha={:.4}, beta={:.4}) \
         crate=(omega={:.4}, alpha={:.4}, beta={:.4}) \
         statsforecast=(omega={:.4}, alpha={:.4}, beta={:.4})",
        true_dgp.omega,
        true_dgp.alpha,
        true_dgp.beta,
        model.omega(),
        model.alpha_params()[0],
        model.beta_params()[0],
        sf.coeff_omega,
        sf.coeff_alpha,
        sf.coeff_beta,
    );

    assert!(model.omega().is_finite(), "crate omega must be finite");
    assert!(
        model.alpha_params()[0].is_finite(),
        "crate alpha must be finite"
    );
    assert!(
        model.beta_params()[0].is_finite(),
        "crate beta must be finite"
    );
    assert!(
        model.omega() < 10000.0 - 1e-9,
        "H2 check: crate omega ({}) should not be pinned to the upper optimizer bound 10000 \
         on a series whose true omega is {}",
        model.omega(),
        true_dgp.omega
    );
}

#[test]
fn garch_forecast_variance_matches_closed_form() {
    let fixture = load_fixture();
    for (name, values) in &fixture.series_values {
        let model = fit_crate_garch(values);
        let horizon = 12;
        let api_forecast = model.forecast_variance(horizon).unwrap();
        let closed_form = closed_form_variance_forecast(&model, values, horizon);

        assert_eq!(api_forecast.len(), closed_form.len(), "series {name}");
        for h in 0..horizon {
            let api = api_forecast[h];
            let cf = closed_form[h];
            let rel_diff = if cf.abs() > 1e-12 {
                (api - cf).abs() / cf.abs()
            } else {
                (api - cf).abs()
            };
            assert!(
                rel_diff < 1e-10,
                "series {name} h={h}: forecast_variance()={api} vs closed-form={cf} (rel diff {rel_diff})"
            );
        }
    }
}

/// H1: simulate 1000 continuations of 12 steps from the TRUE GARCH(1,1) parameters,
/// starting from the actual final (y, sigma2) state of the simulated series, and check
/// the crate's `predict_with_intervals` bounds (from a model fit on that same series)
/// against the empirical distribution of the true continuations.
#[test]
fn garch_interval_coverage_on_true_dgp() {
    let fixture = load_fixture();
    let true_dgp = &fixture.true_dgp;
    let values = fixture.series_values["simulated_zero_mean"].clone();

    // Reconstruct the TRUE sigma2 path deterministically from the TRUE parameters and the
    // observed y series (sigma2 is a pure function of omega/alpha/beta + y history, so this
    // exactly reproduces what the Python generator computed internally).
    let n = values.len();
    let mut true_sigma2 = vec![0.0; n];
    true_sigma2[0] = true_dgp.omega / (1.0 - true_dgp.alpha - true_dgp.beta);
    for t in 1..n {
        true_sigma2[t] = true_dgp.omega
            + true_dgp.alpha * values[t - 1].powi(2)
            + true_dgp.beta * true_sigma2[t - 1];
    }

    let last_y = values[n - 1];
    let last_sigma2 = true_sigma2[n - 1];

    let horizon = 12usize;
    let n_continuations = 1000usize;
    let mut continuations: Vec<Vec<f64>> = Vec::with_capacity(n_continuations);

    for sim in 0..n_continuations {
        let mut rng = StdRng::seed_from_u64(1000 + sim as u64);
        let mut y_prev = last_y;
        let mut sigma2_prev = last_sigma2;
        let mut path = Vec::with_capacity(horizon);
        for _ in 0..horizon {
            let sigma2_next =
                true_dgp.omega + true_dgp.alpha * y_prev * y_prev + true_dgp.beta * sigma2_prev;
            let z: f64 = rng.sample(rand_distr_standard_normal());
            let y_next = z * sigma2_next.sqrt();
            path.push(y_next);
            y_prev = y_next;
            sigma2_prev = sigma2_next;
        }
        continuations.push(path);
    }

    let model = fit_crate_garch(&values);
    let forecast = model.predict_with_intervals(horizon, 0.95).unwrap();
    assert!(forecast.has_lower() && forecast.has_upper());
    let lower = forecast.lower_series(0).unwrap();
    let upper = forecast.upper_series(0).unwrap();

    for h in 0..horizon {
        let covered = continuations
            .iter()
            .filter(|path| path[h] >= lower[h] && path[h] <= upper[h])
            .count();
        let coverage = covered as f64 / n_continuations as f64;
        println!(
            "garch_interval_coverage_on_true_dgp: h={} coverage={:.4} lower={:.4} upper={:.4}",
            h + 1,
            coverage,
            lower[h],
            upper[h]
        );
        // Shipped-outcome assertion (D-10, FIX): predict_with_intervals now centres bounds
        // on the fitted conditional mean (garch.rs, finding H1) instead of predict()'s
        // simulated-innovation draw, restoring coverage to nominal.
        assert!(
            (0.92..=0.98).contains(&coverage),
            "h={}: empirical 95% coverage {} outside [0.92, 0.98] (lower={}, upper={})",
            h + 1,
            coverage,
            lower[h],
            upper[h]
        );
    }
}

#[test]
fn garch_width_vs_statsforecast() {
    let fixture = load_fixture();
    for (name, values) in &fixture.series_values {
        let sf = &fixture.statsforecast[name];
        let model = fit_crate_garch(values);
        let forecast = model.predict_with_intervals(12, 0.95).unwrap();
        let lower = forecast.lower_series(0).unwrap();
        let upper = forecast.upper_series(0).unwrap();

        for h in 0..12 {
            let crate_width = upper[h] - lower[h];
            let sf_width = sf.hi_95[h] - sf.lo_95[h];
            let ratio = if sf_width.abs() > 1e-12 {
                crate_width / sf_width
            } else {
                f64::NAN
            };
            println!(
                "garch_width_vs_statsforecast: series={name} h={} crate_width={:.4} sf_width={:.4} ratio={:.4}",
                h + 1,
                crate_width,
                sf_width,
                ratio
            );
        }
    }
}

/// Minimal standard-normal sampler usable with `rand::Rng::sample`, avoiding a new
/// `rand_distr`/`statrs`-distribution dependency for this test-only harness.
fn rand_distr_standard_normal() -> StandardNormal {
    StandardNormal
}

struct StandardNormal;

impl rand::distributions::Distribution<f64> for StandardNormal {
    fn sample<R: Rng + ?Sized>(&self, rng: &mut R) -> f64 {
        // Box-Muller transform.
        let u1: f64 = rng.gen::<f64>().max(1e-300);
        let u2: f64 = rng.gen();
        (-2.0 * u1.ln()).sqrt() * (2.0 * std::f64::consts::PI * u2).cos()
    }
}
