//! Parity tests against R `forecast::thetaf` (UPST-04).
//!
//! Fixtures are generated by `validation/reference/r/theta.R` (pinned to
//! `forecast` 9.0.2) and stored as JSON under `tests/data/r_reference/`.
//! Each fixture records a series' `theta_model`/`forecast.theta_model` fit:
//! alpha, l0, final level, drift, b, sigma2, the SES SSE, the seasonal
//! component (when present), and the point/lower/upper forecasts at
//! h = 1..24 for both the 80% and 95% levels.
//!
//! This file loads each fixture, fits the crate's `Theta` model on the
//! identical series, and asserts the crate's estimates / forecasts match
//! R's thetaf within the tolerances documented per test.

use std::collections::HashMap;
use std::fs;
use std::path::PathBuf;

use anofox_forecast::core::TimeSeries;
use anofox_forecast::models::theta::Theta;
use anofox_forecast::models::Forecaster;
use chrono::{Duration, TimeZone, Utc};
use serde::Deserialize;

#[derive(Debug, Deserialize)]
#[allow(dead_code)]
struct SeriesBlock {
    name: String,
    n: usize,
    frequency: usize,
    seasonal: bool,
    alpha: f64,
    l0: f64,
    final_level: f64,
    b: f64,
    drift: f64,
    sigma2: f64,
    sse: f64,
    seas_component: Option<Vec<f64>>,
    point: Vec<f64>,
    lower_80: Vec<f64>,
    upper_80: Vec<f64>,
    lower_95: Vec<f64>,
    upper_95: Vec<f64>,
    fitted: Vec<f64>,
    values: Vec<f64>,
}

#[derive(Debug, Deserialize)]
#[allow(dead_code)]
struct Fixture {
    provenance: serde_json::Value,
    horizon: usize,
    series: HashMap<String, SeriesBlock>,
}

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("data")
        .join("r_reference")
}

fn load_fixture() -> Fixture {
    let path = fixtures_dir().join("theta_thetaf.json");
    let raw =
        fs::read_to_string(&path).unwrap_or_else(|_| panic!("missing fixture: {}", path.display()));
    serde_json::from_str(&raw)
        .unwrap_or_else(|e| panic!("malformed fixture {}: {}", path.display(), e))
}

fn make_timestamps(n: usize) -> Vec<chrono::DateTime<Utc>> {
    (0..n)
        .map(|i| Utc.with_ymd_and_hms(2020, 1, 1, 0, 0, 0).unwrap() + Duration::days(i as i64))
        .collect()
}

fn relative_diff(got: f64, want: f64) -> f64 {
    if want.abs() < 1e-12 {
        (got - want).abs()
    } else {
        (got - want).abs() / want.abs()
    }
}

/// Fit `Theta::new()` (STM) on the random-walk fixture series and assert the
/// crate's SES estimation (alpha + initial level, jointly minimised SSE)
/// matches R's `thetaf` within tolerance, and that the h=1 interval
/// half-width (which does not depend on the drift/variance-growth factor
/// fixed later in this plan) is already close to R's.
#[test]
fn theta_stm_matches_thetaf_rw() {
    let fixture = load_fixture();
    let block = fixture
        .series
        .get("rw")
        .expect("rw series missing from fixture");

    let timestamps = make_timestamps(block.values.len());
    let ts = TimeSeries::univariate(timestamps, block.values.clone()).unwrap();

    let mut model = Theta::new();
    model.fit(&ts).unwrap();

    let alpha = model.alpha().expect("alpha must be set after fit");
    assert!(
        (alpha - block.alpha).abs() <= 0.01,
        "alpha {} not within 0.01 of R's {}",
        alpha,
        block.alpha
    );

    // residual_variance is private to the model; back out the crate's SSE
    // at its optimum via the public h=1 95% interval (at h=1, thetaf's and
    // the crate's PRE-Task-2 interval factor both reduce to 1.0, so
    // half_width = z * sqrt(residual_variance) exactly) and assert it does
    // not exceed R's SSE (crate's optimizer must be at least as good,
    // within numerical slack): SSE_crate = residual_variance * (n - 2).
    let n = block.n as f64;
    let fc = model.predict_with_intervals(1, 0.95).unwrap();
    let z95 = 1.959963984540054_f64; // qnorm(0.975)
    let half_width = (fc.upper_series(0).unwrap()[0] - fc.primary()[0]).abs();
    let implied_variance = (half_width / z95).powi(2);
    let implied_sse = implied_variance * (n - 2.0);

    assert!(
        implied_sse <= block.sse * (1.0 + 1e-6) + 1e-6,
        "crate SSE at its optimum ({}) exceeds R's SSE ({})",
        implied_sse,
        block.sse
    );

    // h=1 interval half-width within 1% relative of R's (does not depend on
    // the drift/variance-growth factor fixed in Task 2 of this plan, since
    // at h=1 thetaf's se_1 = sqrt(sigma2) regardless of alpha).
    let r_half_width_95 = (block.upper_95[0] - block.point[0]).abs();
    assert!(
        relative_diff(half_width, r_half_width_95) <= 0.01,
        "h=1 95% half-width {} not within 1% of R's {}",
        half_width,
        r_half_width_95
    );
}
